astrobin/astrobin

astrobin_apps_notifications/types.py, astrobin_apps_premium/management/commands/send_renewal_notifications.py, astrobin_apps_premium/templates/notification/expiring_subscription/full.txt, astrobin_apps_premium/templates/notification/expiring_subscription_autorenew/full.txt, astrobin_apps_premium/templates/notification/expiring_subscription_autorenew/notice.html, astrobin_apps_premium/templates/notification/expiring_subscription_autorenew/short.html, astrobin_apps_premium/templates/notification/expiring_subscription_autorenew/short.txt
=> (emails) Send specific email to autorenewing members

astrobin/tasks.py
=> (tasks) Fix IOTD API sync command

astrobin/settings/components/basic.py, common/api_urls.py, common/serializers.py, common/views.py, nested_comments/static/nested_comments/js/nested_comments_app.js
=> (comments) Fetch real name from new UserProfile API

astrobin/templates/contact_form/contact.html
=> Add notice to contact form re contacting the staff

requirements.txt
=> Remove unnecessary package that causes a build failure (#596)

docker/docker-compose.yml
=> Move beat pidfile local to container, #574

astrobin/templates/avatar/change.html
=> (profile) Add HTML head title to avatar page

docker/docker-compose.build.yml
Makes it easier to develop locally.
=> (docker) Export ports, share code with compose

astrobin/static/astrobin/scss/astrobin.scss, astrobin_apps_users/templates/astrobin_apps_users/inclusion_tags/astrobin_user.html
=> (profile) Add short cut to editing own avatar

astrobin/models.py, astrobin/templates/vue_frontend/search_app/components/remote_source_filter_component.vue.html
=> (images) Add Lijiang observatory to the list of remote sources

astrobin_apps_platesolving/templates/astrobin_apps_platesolving/inclusion_tags/platesolving_machinery.html, astrobin_apps_platesolving/utils.py
=> (platesolving) Prevent "placeholder" image from being plate-solved

astrobin/static/astrobin/scss/astrobin.scss, astrobin/templates/pybb/latest_topics.html, astrobin/templates/pybb/topic.html, astrobin/templates/pybb/topic_list.html, astrobin/tests/test_forum.py, astrobin/urls.py, astrobin/views/moderation.py
=> (forum) Add support for content moderator to mark as spam multiple topics

astrobin_apps_notifications/backends.py, astrobin_apps_notifications/tests/email_backend_test.py, astrobin_apps_notifications/tests/notifications_test.py
=> (email) Do not deliver email to addresses with a complaint

astrobin/templates/faq.html
=> (docs) Fix FAQ links

astrobin/management/commands/add_missing_image_sizes.py, astrobin/management/commands/fix_revision_labels.py, astrobin/management/commands/guess_subject_type.py, astrobin/management/commands/reset_lite_counters.py, astrobin/models.py, astrobin/signals.py, astrobin/tests/common.py, astrobin/tests/test_explore.py, astrobin/tests/test_gear.py, astrobin/tests/test_image.py, astrobin/tests/test_moderation.py, astrobin/tests/test_user.py, astrobin/views/__init__.py, astrobin/views/image.py, astrobin/views/registration.py, astrobin_apps_groups/tests.py, astrobin_apps_images/templatetags/astrobin_apps_images_tags.py, astrobin_apps_iotd/tests.py, astrobin_apps_premium/tests.py, common/tests.py
=> (images) Prevent deleted images from getting undeleted

astrobin_apps_iotd/tests.py, astrobin_apps_iotd/views.py
=> (iotd) Prevent deleted images to still appear on IOTD archive

astrobin/templates/image/detail/image_card.html, astrobin/templatetags/tags.py, astrobin/tests/test_tags.py
=> (images) Use hours/min/sec and degrees/min/sec for RA/dec

astrobin/templates/vue_frontend/search_app/components/acquisition_type_filter_component.vue.html
=> (search) Add Drawing/Sketch to acquisition type search filter

astrobin/models.py, astrobin/search_indexes.py, astrobin/templates/inclusion_tags/search_image_list.html
=> (search) Do not show comments belonging to deleted images

astrobin/templates/image/detail.html, astrobin/templates/image/detail/modals/delete.html, astrobin/templates/image/detail/modals/delete_revision.html, astrobin/templates/image/edit/revision.html
=> (images) Add button to delete revision from edit revision image

docker/astrobin.dockerfile
=> (infra) Pin setuptools at < 45 because newer versions won't support Python 2

astrobin/templates/image/detail/info.html
It was supposed to be a button to bookmark your own image but accidentally made you bookmark yourself as a user. Utterly useless.
=> (images) Remove user bookmark

astrobin/settings/environments/debug.py, astrobin_apps_users/templates/astrobin_apps_users/inclusion_tags/astrobin_username.html, astrobin_apps_users/templatetags/astrobin_apps_users_tags.py
=> (general) Cache usernames by language code too

astrobin/templates/image/detail/menu/view.html, astrobin/templates/image/full.html, astrobin/tests/test_image.py, astrobin/views/image.py, astrobin_apps_premium/templatetags/astrobin_apps_premium_tags.py
=> (images) Fix incorrect permissions to view real size images

astrobin/flickr.py, astrobin/search_indexes.py, astrobin/settings/environments/debug.py, astrobin/templates/user/profile/flickr_import.html, astrobin/views/__init__.py
Additionally, fix duplicated search property
=> (debug) Add logs to search and flickr

README.md, astrobin/settings/components/basic.py, astrobin/settings/environments/testing.py, scripts/docker-reset.sh, scripts/test.sh
Additionally:
* Fix docker-reset.sh script
* Fix testing instructions in README.md
=> (infra) Fix execution of test command on pristine build

astrobin/tests/test_image.py, astrobin/views/image.py
=> (images) Drop solution when changing image in edit basic info

astrobin/tests/generators.py, astrobin_apps_premium/tasks.py, astrobin_apps_premium/tests/test_reactivate_previous_subscription.py
=> (premium) Include autorenew when reactivating previous subscription after free Ultimate expires

requirements.txt
=> (deps) Upgrade numpy to 1.16.6

astrobin_apps_notifications/api/views.py
Closes astrobin/astrobin-ng#147
=> (api) Use CamelCaseJSONParser for notifications

astrobin/urls.py, docker/nginx.beta.conf, docker/nginx.prod.conf
=> (general) Fix serving /favicon.ico

astrobin/settings/components/logging.py, astrobin/views/__init__.py, astrobin_apps_platesolving/views/solution.py
Also, have revision inherit advanced settings from mother image.
Closes #861
=> (plate-solving) Make images inherit advanced settings from recent image

astrobin_apps_platesolving/annotate.py, astrobin_apps_platesolving/views/solution.py
=> (plate-solving) Use HD (and when available, sharpened) image to annotate

astrobin/templates/pybb/post_template.html, common/templatetags/common_tags.py, requirements.txt
=> (forums) Forbid editing posts 5 minutes after creation

astrobin/templates/el_pagination/show_pages.html, astrobin_apps_groups/templates/astrobin_apps_groups/group_members_list.html, astrobin_apps_groups/templates/astrobin_apps_groups/group_members_list_entries.html, astrobin_apps_groups/views/group_members_list.py, requirements.txt
Downgrade el-pagination back to version that supports Python 2 and
fix API changes.
Closes #1222
=> (general) Fix pagination issue

astrobin/tests/test_image.py, astrobin/views/image.py
=> (images) Do display gain also when it's 0

astrobin/models.py, astrobin/templates/image/detail/modals/upload_revision.html, astrobin/tests/test_image.py, astrobin/views/__init__.py, astrobin_apps_images/api/filters/__init__.py, astrobin_apps_images/api/filters/image_revision_filter.py, astrobin_apps_images/api/filters/thumbnail_group_filter.py, astrobin_apps_images/api/mixins/tus_cache_mixin.py, astrobin_apps_images/api/mixins/tus_create_mixin.py, astrobin_apps_images/api/mixins/tus_patch_mixin.py, astrobin_apps_images/api/serializers/__init__.py, astrobin_apps_images/api/serializers/image_revision_serializer.py, astrobin_apps_images/api/serializers/image_serializer.py, astrobin_apps_images/api/serializers/thumbnail_group_serializer.py, astrobin_apps_images/api/urls.py, astrobin_apps_images/api/utils.py, astrobin_apps_images/api/views/__init__.py, astrobin_apps_images/api/views/image_revision_view_set.py, astrobin_apps_images/api/views/image_view_set.py, astrobin_apps_images/api/views/thumbnail_group_view_set.py, astrobin_apps_images/services/image_service.py, astrobin_apps_images/tests/test_image_service.py
=> (images) Add support for chunked image revision uploads

astrobin/tests/test_image.py, astrobin/views/image.py
=> (image) Fix display of "bin 0x0" when binning has not been specified

astrobin/static/astrobin/scss/astrobin.scss, astrobin/templates/user/profile.html, astrobin/tests/test_user.py, astrobin/views/__init__.py, astrobin_apps_images/templates/astrobin_apps_images/snippets/image.html, astrobin_apps_images/templatetags/astrobin_apps_images_tags.py
=> (images) Show WIP images in main gallery with lock icon

astrobin/forms/promote_form.py, astrobin/static/astrobin/scss/modal.scss, astrobin/templates/image/detail/modals/demote.html, astrobin/templates/image/detail/modals/promote.html, astrobin/templates/image/detail/wip_banner.html, astrobin/tests/test_image.py, astrobin/views/image.py, astrobin_apps_images/api/views/image_view_set.py
=> (images) Add option to skip notifications when promoting image to public area

astrobin/static/astrobin/scss/astrobin.scss, astrobin/static/astrobin/scss/nav.scss, astrobin/templates/image/detail/revisions.html
=> (images) Add contextual menu for revisions, incl. entry to mark as final

nested_comments/templates/nested_comments/nestedcomment_app.html
=> (comments) Do not show user avatar of authors of deleted comments

cypress/integration/forums.js, cypress/integration/image-upload.js, cypress/integration/login.js, cypress/support/commands/accept-cookies.js, cypress/support/commands/login.js, requirements.txt, scripts/init.sh
=> (deps) Upgrade forum to latest upstream version

requirements.txt
=> (forms) Do notify subscribers when posts are edited

astrobin/templates/base.html
=> (general) Fix "back to top" link in the footer

astrobin/tests/test_moderation.py, astrobin/views/moderation.py
=> (moderation) Delay image moderation queue by 10 minutes to allow uploads to complete

README.md, astrobin/settings/components/celery.py, docker/docker-compose.build.yml, docker/docker-compose.deploy.yml, docker/docker-compose.yml, requirements.txt
=> (infra) Move from rabbitmq to redis as celery broker

astrobin/static/astrobin/scss/astrobin.scss
=> (images) Fix displaying of badges on revisions

astrobin/templates/base/meta.html, astrobin/templates/error_base.html, astrobin/templates/image/full.html, astrobin/templates/maintenance_base.html
=> (mobile) Add meta theme-color

astrobin/api.py
=> (api/v1) Add count of likes, bookmarks, comments, views to the Image v1 API

astrobin/templates/notification/api_key_request_approved/full.html, astrobin/templates/notification/api_key_request_approved/full.txt, astrobin/templates/notification/api_key_request_approved/notice.html, astrobin/templates/notification/api_key_request_approved/short.html, astrobin/templates/notification/api_key_request_approved/short.txt, astrobin/templates/notification/email_body.txt, astrobin/templates/notification/new_bookmark/full.html, astrobin/templates/notification/new_bookmark/full.txt, astrobin/templates/notification/new_bookmark/notice.html, astrobin/templates/notification/new_bookmark/short.html, astrobin/templates/notification/new_bookmark/short.txt
=> (notifications) Improve API key acceptance and bookmark notifications

astrobin/templates/messages/view.html
=> (private-messages) Move 'Delete conversion' button to the bottom

astrobin/templates/base/footer.html, astrobin/templates/base/meta.html, astrobin/templates/error_base.html, astrobin/templates/maintenance_base.html
- Change website tagline to something shorter and more descriptive
- Add platform updates link that takes you to the #astrobintech Twitter feed
- Add PixInsight to the footer as a third party tool
- Include meta and footer templates from mainenance_base.html to remove repetition
=> (general) Apply various minor base template changes

astrobin/static/astrobin/scss/astrobin.scss, astrobin/static/astrobin/scss/reputation-leaderboard.scss, astrobin/static/astrobin/scss/trending-astrophotographers.scss, astrobin/templates/_reputation_alert.html, astrobin/templates/base/site_links.html, astrobin/templates/base/user_links.html, astrobin/templates/reputation_leaderboard.html, astrobin/templates/trending_astrophotographers.html, astrobin/views/__init__.py, common/services/pagination_service.py, common/templatetags/common_tags.py, common/tests/test_pagination_service.py
- Fix right alignment of last table item
- Add search capability
- Add pagination to trending
- Add secondary sorting
- Fix pagination counter
Closes #1578, closes #1579, closes #1582, closes #1583, closes #1584
=> (reputation/trending) Various improvements and fixes

astrobin/templates/image/detail.html, astrobin/templates/image/detail/like.html, astrobin/templates/image/detail/modals/cant_unlike.html, astrobin/templates/pybb/post_template.html, astrobin/templatetags/tags.py, astrobin/tests/generators.py, astrobin_apps_users/services/user_service.py, astrobin_apps_users/tests/test_user_service.py, common/views.py, nested_comments/static/nested_comments/js/nested_comments_app.js, toggleproperties/templates/toggleproperties/toggleproperty_add_remove.html, toggleproperties/templatetags/toggleproperty_tags.py
=> (likes) Forbid removing likes older than 1 hour

nested_comments/static/nested_comments/js/nested_comments_app.js, nested_comments/templates/nested_comments/nestedcomment_app.html
=> (comments) Display created timestamp instead of updated

astrobin/templates/reputation_leaderboard.html, astrobin/templates/trending_astrophotographers.html
=> (reputation/trending) Do not display position if there's a search term

astrobin/templates/actstream/_action_image_like.html
=> (images) Disallow unliking after 1h also on homepage action stream

astrobin/views/__init__.py
It's not fair for me to be there because I get lots of points from announcements.
=> (reputation) Exclude user 'siovene' from reputation leaderboard

astrobin_apps_images/api/serializers/image_revision_serializer.py, astrobin_apps_images/api/serializers/image_serializer.py, astrobin_apps_images/api/views/image_revision_view_set.py, astrobin_apps_images/api/views/image_view_set.py, docker/docker-compose-app.yml
=> (api/v2) Accept w/h params for Image/ImageRevision to avoid fetching them from storage

astrobin/static/astrobin/scss/astrobin.scss, astrobin/templates/image/detail/modals/share.html
=> (images) Fix UI of Share dialog on mobile

astrobin/static/astrobin/scss/astrobin-mobile.scss, astrobin/templates/image/detail/image_card.html
=> (general) Fix width of subtle-container headers on mobile

astrobin/context_processors.py, astrobin/templates/actstream/action.html, astrobin/templatetags/tags.py, astrobin/tests/test_home.py
=> (action-stream) Fix action template fragment caching

astrobin_apps_notifications/types.py, astrobin_apps_premium/management/commands/send_expiring_subscription_autorenew_notifications.py, astrobin_apps_premium/templates/notification/expiring_subscription_autorenew_30d/full.txt, astrobin_apps_premium/templates/notification/expiring_subscription_autorenew_30d/notice.html, astrobin_apps_premium/templates/notification/expiring_subscription_autorenew_30d/short.html, astrobin_apps_premium/templates/notification/expiring_subscription_autorenew_30d/short.txt
=> (emails) Send expiraton reminder also 30 days before, for old autorenew subscriptions

astrobin/templates/notification/new_comment_like/full.html
=> (notifications) Only show 100 characters of the liked comment

astrobin/static/astrobin/scss/astrobin.scss, astrobin/templates/image/full.html
=> (images) Remove 'click to go back to regular' as it was confusing with the zoom

astrobin/templates/image/full.html, astrobin/templatetags/tags.py
=> (images) Allow click-and-drag zoom long as the image is wider than the window

astrobin_apps_users/services/user_service.py, astrobin_apps_users/tests/test_user_service.py
=> (forums) Do not allow likes on posts in closed topics

astrobin/api.py
=> (api/v1) Add data_source and remote_source attributes to ImageResource

astrobin_apps_images/api/serializers/image_serializer.py, astrobin_apps_images/api/views/image_view_set.py
=> (images) Fix keeping default license after upload from beta uploader

astrobin/templates/image/detail/image_title.html, astrobin/templates/image/detail/revisions.html
=> (images) Add link to download original file, only visible to owner

astrobin/api.py
=> (api/v1) Add histogram and skyplot URLs to the  

astrobin/forms/edit_watermark_form.py, astrobin/templates/image/edit/watermark.html
=> (images) Remove untrue information from watermark help text

astrobin/templates/image/detail.html, astrobin/templates/image/detail/modals/full-subject-list.html
=> (images) Don't show more than than 30 deep sky subjects, it gets crowded

astrobin/templates/base/footer.html
=> (general) Add Jean-Baptiste Auroux and Nadir Teymurov to the "thanks to" section

astrobin/templatetags/tags.py
=> (ads) Do not show adsense ads on registratios and login pages

astrobin/settings/components/payments.py, astrobin/urls.py, astrobin_apps_payments/api/filters/exchange_rate_filter.py, astrobin_apps_payments/api/serializers/exchange_rate_serializer.py, astrobin_apps_payments/api/urls.py, astrobin_apps_payments/api/views/exchange_rate_view_set.py, astrobin_apps_payments/api/views/pricing_view.py, astrobin_apps_payments/models.py, astrobin_apps_payments/services/pricing_service.py, astrobin_apps_payments/tests.py, astrobin_apps_payments/tests/test_pricing_service.py, astrobin_apps_payments/views.py
=> (payments) Use exchange rate to show correct price conversion from CHF

cypress/integration/register.js, cypress/support/commands/index.js, cypress/support/commands/register.js, cypress/support/commands/utils.js
This test creates a user with a random username/email.  Deleting the user after the test would probably be ideal, but I don't think that deleting the account in the frontend actually deletes it from the database.
=> Add registration test

cypress/integration/forums.js
Tests likes, smileys, bold text, italic text, and links.
=> Add forum tests

astrobin_apps_iotd/api/views/submission_queue_view_set.py, astrobin_apps_iotd/services/iotd_service.py, astrobin_apps_iotd/tests/test_iotd.py, astrobin_apps_iotd/views.py
=> (iotd) Apply filter by designated submitters/reviewers

astrobin/templates/pybb/post_template.html, requirements.txt
=> (forums) Bump deadline for editing from 5 to 15 minutes

astrobin/signals.py
=> (forums) Drop the various *** Type your message here *** after a quote reply

astrobin_apps_iotd/services/iotd_service.py, astrobin_apps_iotd/tests/test_iotd_service.py
=> (iotd) Fix temporal hole when an image would lose TPN status before gaining TP status

astrobin/signals.py, astrobin_apps_users/services/user_service.py, astrobin_apps_users/tests/test_user_service.py
=> (iotd) Exclude image owner when building designated submitters/reviewer

astrobin_apps_images/api/mixins/tus_patch_mixin.py
=> (images) Perform asynchronous retrieval of primary thumbnails in case of API upload

astrobin/settings/components/basic.py, astrobin/templates/upload.html
=> (images) Allow TIF files to be uploaded

astrobin/context_processors.py, astrobin/templates/base/global_alerts.html, astrobin_apps_notifications/backends.py, astrobin_apps_notifications/tests/email_backend_test.py, common/services/email_service.py
=> (emails) If there's a successful delivery after a bounce, keep sending emails to that address

astrobin_apps_iotd/services/iotd_service.py, astrobin_apps_iotd/tests/test_iotd_service.py
=> (iotd) Exclude images voted yesterday from a reviewer's queue

astrobin/static/astrobin/scss/astrobin.scss, astrobin/static/astrobin/scss/forum.scss, astrobin/templates/index/root.html, astrobin/templates/pybb/forum_list.html, astrobin/templates/pybb/index.html, astrobin/templates/pybb/topic_last_message_info.html, astrobin/templates/pybb/topic_list.html
Closes #1825, closes #1827, closes #1828
=> (forums) Apply various UI improvements

astrobin/static/astrobin/scss/forum.scss, astrobin/templates/pybb/_forum_tools.html, astrobin/templates/pybb/breadcrumb.html, astrobin/templates/pybb/forum.html, astrobin/templates/pybb/latest_topics.html
=> (forums) Make "New topic" button more visible, add search box, increase page size

astrobin/settings/components/forum.py, astrobin/tests/test_forum.py
=> (forums) Auto approve post if user has an approved topic

astrobin/templatetags/tags.py
=> (general) Fix name of Turkish language

astrobin/urls.py
=> (general) Remove trailing $ from PayPal IPN urls

astrobin/signals.py, nested_comments/tests/test_comment_approval.py
=> (comments) Automatically approve comments if you already have 3 approved ones

astrobin/static/astrobin/scss/accordion.scss, astrobin/static/astrobin/scss/astrobin.scss, astrobin/templates/base/global_alerts.html, astrobin_apps_users/urls.py, astrobin_apps_users/views.py
=> (emails) Make bounces/complaint warning less invasive and add button to remove them

astrobin/static/astrobin/scss/accordion.scss, astrobin/static/astrobin/scss/alert.scss, astrobin/templates/base/global_alerts.html, astrobin_apps_premium/templatetags/astrobin_apps_premium_tags.py, astrobin_apps_premium/utils.py
=> (subscriptions) Add global banner to inform about expired subscription

astrobin/middleware/last_seen_middleware.py, astrobin/signals.py, astrobin/templates/notification/new_payment/full.html, astrobin/templates/notification/new_payment/full.txt, astrobin/templates/notification/new_payment/notice.html, astrobin/templates/notification/new_payment/short.html, astrobin/templates/notification/new_payment/short.txt, astrobin/templates/notification/new_subscription/full.txt, astrobin/tests/test_subscriptions.py, astrobin_apps_notifications/templatetags/astrobin_apps_notifications_tags.py, astrobin_apps_notifications/types.py, requirements.txt
=> (subscriptions) Extend by one year from the previous expiration if renewing before expiration

astrobin_apps_platesolving/backends/astrometry_net/solver.py
This makes it easier to change it if needed.
=> (plate-solving) Use base_url variable to reference astrometry.net

requirements.txt
=> (deps) Remove unneeded dependency python-http-client (from Sendgrid)

astrobin/templates/index/root.html
=> (performance) Remove home page stream caching because it breaks mini like buttons

astrobin/static/astrobin/scss/alert.scss, astrobin/tests/test_image.py, astrobin/views/image.py
=> (images) Redirect to final revision if request references invalid revision

astrobin/static/astrobin/scss/astrobin.scss, astrobin/templates/image/detail/revisions.html
=> (images) Highlight revision currently being viewed

astrobin/tests/generators.py, astrobin/tests/test_image.py, astrobin/views/image.py, astrobin_apps_images/services/image_service.py, astrobin_apps_images/tests/test_image_service.py, astrobin_apps_platesolving/tests/platesolving_generators.py
=> (images) When deleting the original image, make the oldest revision the new original

astrobin/search.py, astrobin/templates/image/detail/image_card.html, astrobin/templates/vue_frontend/search_app/app.vue.html, astrobin/templates/vue_frontend/search_app/components/date_acquired_filter_component.vue.html, astrobin/templates/vue_frontend/search_app/index.html
=> (search) Add search by acquisition date range

astrobin/settings/components/toggleproperties.py, astrobin/static/astrobin/scss/astrobin.scss, astrobin/static/astrobin/scss/nav.scss, astrobin/templates/image/detail/image_title.html, astrobin/templates/image/full.html, toggleproperties/templates/toggleproperties/toggleproperty_add_remove.html, toggleproperties/templatetags/toggleproperty_tags.py
=> (images) Add Like button to full size view

astrobin/static/astrobin/js/astrobin.js, astrobin/templates/base/js.html
=> (notifications) Automatically mark as read when clicked in the notifications modal

astrobin/signals.py, astrobin/templates/notification/congratulations_for_your_first_image/notice.html
=> (notifications) Link the "congrats for your first image" notification to the image

astrobin/templates/image/detail/modals/_delete_from_free_info.html, astrobin/templates/image/detail/modals/delete.html
=> (images) Add info message about upload counter when you're on Free and want to delete an image

astrobin/views/__init__.py
=> (frontpage) The recent images section should be sorted by publication date, not upload date

astrobin/static/astrobin/scss/activity-actions.scss, astrobin/static/astrobin/scss/astrobin.scss, astrobin/static/astrobin/scss/nav.scss, astrobin/templates/actstream/_action_image_title.html, astrobin/templates/actstream/action.html, astrobin/templates/base/user_links.html, astrobin/templates/index/root.html, astrobin_apps_iotd/templates/astrobin_apps_iotd/iotd_archive.html, astrobin_apps_users/templates/astrobin_apps_users/inclusion_tags/astrobin_username.html
=> (ui) Improve space taken by usernames and do various related UI fixes

astrobin/templates/notification/comment_approved/full.html, astrobin/templates/notification/comment_approved/full.txt, astrobin/templates/notification/comment_approved/notice.html, astrobin/templates/notification/comment_approved/short.html, astrobin/templates/notification/comment_approved/short.txt, astrobin_apps_notifications/types.py, nested_comments/admin.py, nested_comments/services/comment_notifications_service.py
=> (notifications) Add notification when a comment is approved

astrobin/search.py, astrobin/static/astrobin/scss/search.scss, astrobin/templates/vue_frontend/search_app/app.vue.html, astrobin/templates/vue_frontend/search_app/components/integration_time_filter_component.vue.html, astrobin/templates/vue_frontend/search_app/index.html
=> (search) Add search by integration time in hours

astrobin/static/astrobin/scss/alert.scss, astrobin/static/astrobin/scss/nav.scss, astrobin/templates/base.html, astrobin/templates/image/detail.html
=> (images) Move moderation and WIP alerts to the top of the page

astrobin/templates/user/profile.html
New users might not be able to find their new uploads.
Closes #2034
=> (users) Add personal alert if all images are in the Staging area

astrobin/static/astrobin/scss/nav.scss, astrobin/templates/user/profile.html, astrobin/templates/user/profile/image_navigation_menu.html, astrobin/templates/user/profile/meta.html
=> (ui) Move gallery sub-navigation to the top where it's easier to see

astrobin/static/astrobin/scss/astrobin.scss
=> (images) Add obvious "thumbnail too small" warning message

astrobin/middleware/__init__.py, astrobin/middleware/mark_notification_as_read_middleware.py, astrobin/settings/components/middleware.py, astrobin/static/astrobin/js/astrobin.js
This reduces the time to open a notification because we don't have to wait for the ajax call
=> (notifications) Mark as read via middleware only after clicking it

astrobin/settings/components/forum.py, astrobin/static/astrobin/scss/ckeditor.scss, astrobin/static/astrobin/scss/forum.scss
=> (forums) Fix aggressive removal of \n and blockquote margin

astrobin/permissions.py, astrobin/settings/components/forum.py, astrobin/templates/pybb/post_template.html, astrobin/templates/pybb/topic.html, astrobin/templates/pybb/topic_list.html, requirements.txt
=> (forums) Fix some issues with forum permissions and visibility

astrobin/templates/image/full.html, astrobin/views/image.py
=> (images) Disable click-and-zoom and show warning for images > 25 MB

astrobin/widgets/hidden_image_crop_widget.py
=> (images) Make thumbnail editor on image use original revision, not final

astrobin/models.py, astrobin/tests/test_gear.py
=> (equipment) Fix Gear absolute URL to be a search page

astrobin/static/astrobin/scss/nav.scss, astrobin/templates/base/language_switcher.html, astrobin/templatetags/tags.py
=> (general) Use language codes instead of globe icon, for clarity

astrobin_apps_iotd/api/views/hidden_image_view_set.py, astrobin_apps_iotd/api/views/submission_view_set.py, astrobin_apps_iotd/api/views/vote_view_set.py
=> (i18n) Remove localization from strings that are programming error messages

astrobin/middleware/__init__.py, astrobin/middleware/previous_topic_read_marker.py, astrobin/settings/components/middleware.py, astrobin/settings/components/templates.py, astrobin/static/astrobin/scss/forum.scss, astrobin/static/astrobin/scss/toast.scss, astrobin/templates/pybb/post_template.html, astrobin/templates/pybb/topic.html, astrobin/templatetags/tags.py, common/services/forum_service.py, cypress/integration/forums.js
=> (forums) Show "new posts" break and notification, improve looks

astrobin/management/commands/lacking_data_reminder.py, astrobin/management/commands/send_missing_data_source_notifications.py, astrobin/management/commands/send_missing_remote_source_notifications.py, astrobin/middleware/mark_notification_as_read_middleware.py, astrobin/models.py, astrobin/signals.py, astrobin/tasks.py, astrobin/templates/notification/new_image/full.html, astrobin/templates/notification/new_image/full.txt, astrobin/views/moderation.py, astrobin/views/registration.py, astrobin_apps_groups/views/group_approve_join_request.py, astrobin_apps_groups/views/group_invite.py, astrobin_apps_groups/views/group_join.py, astrobin_apps_groups/views/group_reject_join_request.py, astrobin_apps_iotd/tasks.py, astrobin_apps_iotd/tests/test_tasks.py, astrobin_apps_notifications/backends.py, astrobin_apps_notifications/tasks.py, astrobin_apps_notifications/templatetags/astrobin_apps_notifications_tags.py, astrobin_apps_notifications/utils.py, astrobin_apps_notifications/views.py, astrobin_apps_premium/management/commands/send_expired_subscription_notifications.py, astrobin_apps_premium/management/commands/send_expiring_subscription_autorenew_notifications.py, astrobin_apps_premium/management/commands/send_expiring_subscription_notifications.py, nested_comments/services/comment_notifications_service.py, nested_comments/tests/test_comment_notification_service.py
=> (notifications) Pass sender to push_notification so to only mark the correct one per path as read

astrobin/tasks.py
=> (infra) Add task to assign upload length to images that lack it

astrobin/signals.py
=> (subscriptions) Apply new expiration date correctly when there's a time gap from a previous subscription

astrobin/static/astrobin/scss/astrobin.scss, astrobin/static/astrobin/scss/nav.scss, astrobin/templates/image/detail/image_card.html, astrobin_apps_platesolving/services/solution_service.py, astrobin_apps_platesolving/templatetags/astrobin_apps_platesolving_tags.py
=> (images) Add buttons to search around the same field

astrobin/tests/test_image.py, astrobin_apps_premium/templatetags/astrobin_apps_premium_tags.py, astrobin_apps_premium/tests/test_premium.py
=> (subscriptions) Allow free and anonymous to see real resolution images

astrobin_apps_payments/views.py
=> (payments) Do not double process SEPA payments

astrobin/urls.py, astrobin/views/__init__.py, astrobin_apps_donations/urls.py, astrobin_apps_iotd/urls.py, astrobin_apps_json_api/common/urls.py, astrobin_apps_json_api/user/urls.py, astrobin_apps_notifications/urls.py, astrobin_apps_users/urls.py
We use template fragment caching when needed
=> (general) Do not cache dynamic views ever

astrobin/settings/components/thumbnail.py, astrobin/thumbnail_processors.py
=> (images) Fix whiteout issue with 16 bit greyscale TIFF files

astrobin/search_indexes.py, astrobin/templates/image/detail.html, astrobin/views/image.py, astrobin_apps_images/services/image_service.py, common/services/constellations_service.py
=> (images) Add support to show the image's  constellation

astrobin/static/astrobin/js/astrobin.js, astrobin/templates/change_email/emailchange_confirm_delete.html, astrobin/templates/change_email/emailchange_detail.html, astrobin/templates/image/detail/info.html, astrobin/templates/image/detail/revisions.html, astrobin/templates/image/edit/_catastrophic_data_corruption.html, astrobin/templates/inclusion_tags/image_list.html, astrobin/templates/inclusion_tags/search_image_list.html, astrobin/templates/index/root.html, astrobin/templates/messages/inbox.html, astrobin/templates/messages/message_list_view.html, astrobin/templates/pybb/post_template.html, astrobin/templates/pybb/topic_last_message_info.html, astrobin/templates/pybb/topic_list.html, astrobin/templates/user/profile/edit/download_data.html, astrobin/views/__init__.py, astrobin_apps_groups/templates/astrobin_apps_groups/_group_list_table.html, astrobin_apps_groups/templates/astrobin_apps_groups/group_detail.html, astrobin_apps_images/templates/astrobin_apps_images/snippets/image.html, astrobin_apps_notifications/templates/astrobin_apps_notifications/_table_rows.html, astrobin_apps_notifications/templates/astrobin_apps_notifications/all.html, astrobin_apps_premium/templates/astrobin_apps_premium/_transactions.html, common/services/datetime_service.py, common/templatetags/common_tags.py
=> (general) Use frontend exclusively to show timestamps in user's locale and timezone

astrobin/templates/image/detail/menu/user.html, astrobin/templates/user/profile/navigation.html, astrobin_apps_users/services/user_service.py, astrobin_apps_users/tests/test_user_service.py
=> (users) Do not show add/remove shadow-ban entry in menus for anonymous users

astrobin/templates/search/search.html, astrobin/templates/user/profile/navigation.html, astrobin/views/image.py
Do the same for search results and rename "Upload date" in sort menu
=> (images) Sort navigation menu images by publication date first

astrobin/static/astrobin/scss/astrobin.scss, astrobin/templates/image/detail/image.html, astrobin_apps_images/static/astrobin_apps_images/js/astrobin_apps_images.js
=> (images) Show loading indicator while enhancing image with large screen or high DPI version

astrobin/static/astrobin/js/astrobin.js
=> (forums) Fix emoticon path

astrobin/static/astrobin/scss/astrobin-large.scss, astrobin/static/astrobin/scss/astrobin.scss, astrobin/templates/image/detail.html, astrobin/views/image.py, astrobin_apps_images/static/astrobin_apps_images/js/astrobin_apps_images.js
=> (images) Display landscape mode images > 940px using full width of container

astrobin/search_indexes.py
=> (search) Remove hidden forums and categories from search results

astrobin/templates/user/profile.html, astrobin/tests/test_user.py, astrobin/views/__init__.py
=> (gallery) Do not show images lacking acquisition when sorting by acquisition

astrobin/forms/profile_edit_preferences_form.py, astrobin/settings/components/forum.py, astrobin/signals.py, astrobin/templates/notification/new_forum_reply/full.html, astrobin/templates/notification/new_forum_reply/full.txt, astrobin/templates/notification/new_forum_reply/notice.html, astrobin/templates/notification/new_forum_reply/short.html, astrobin/templates/notification/new_forum_reply/short.txt, astrobin_apps_notifications/types.py
=> (forums) Begin using AstroBin native notifications

astrobin/search.py, astrobin/search_indexes.py, astrobin/templates/vue_frontend/search_app/app.vue.html, astrobin/templates/vue_frontend/search_app/components/bortle_scale_filter_component.vue.html, astrobin/templates/vue_frontend/search_app/index.html
=> (search) Add support to search by min/max Bortle Scale value

astrobin/signals.py, astrobin/templates/notification/your_image_is_iotd/full.html, astrobin/templates/notification/your_image_is_iotd/full.txt, astrobin/templates/notification/your_image_is_iotd/notice.html, astrobin/templates/notification/your_image_is_iotd/short.html, astrobin/templates/notification/your_image_is_iotd/short.txt, astrobin/templates/notification/your_image_is_tp/full.html, astrobin/templates/notification/your_image_is_tp/full.txt, astrobin/templates/notification/your_image_is_tp/notice.html, astrobin/templates/notification/your_image_is_tp/short.html, astrobin/templates/notification/your_image_is_tp/short.txt, astrobin/templates/notification/your_image_is_tpn/full.html, astrobin/templates/notification/your_image_is_tpn/full.txt, astrobin/templates/notification/your_image_is_tpn/notice.html, astrobin/templates/notification/your_image_is_tpn/short.html, astrobin/templates/notification/your_image_is_tpn/short.txt, astrobin_apps_iotd/admin.py, astrobin_apps_iotd/tasks.py, astrobin_apps_notifications/types.py
=> (notifications) Add notifications when image becomes TPN/TP/IOTD

astrobin/models.py, astrobin/signals.py, astrobin/tests/test_signals.py, astrobin_apps_notifications/services/__init__.py, astrobin_apps_notifications/services/notifications_service.py, nested_comments/services/__init__.py, nested_comments/services/comment_notifications_service.py
=> (infra) Email super users when comments and forum posts await moderation

astrobin/lookups.py, astrobin/static/astrobin/scss/astrobin.scss, astrobin/templates/image/detail/menu/user.html, astrobin/templates/messages/compose.html, astrobin/urls.py
Additionally, fix issue with "image.title" being passed as a default subject line.
=> (messages) Add support to autocomplete recipients by real name

astrobin/permissions.py, astrobin/templates/base/modals.html, astrobin/templates/pybb/_forum_tools.html, astrobin/templates/pybb/_need_to_join_group_message.html, astrobin/templates/pybb/topic.html, astrobin/tests/test_forum.py, astrobin/tests/test_forum_permissions.py, astrobin_apps_groups/templates/astrobin_apps_groups/group_detail.html, astrobin_apps_groups/tests/test_group_forums.py, astrobin_apps_groups/tests/test_groups.py
=> (groups) Allow people to see public group forums without joining

astrobin/static/astrobin/js/astrobin.js, astrobin/static/astrobin/js/fancybox-4.0.31-patched.umd.js, astrobin/static/astrobin/js/fancybox-4.0.31-patched.umd.min.js, astrobin/templates/base/js.html, astrobin/templates/base/scripts.html, astrobin/templates/image/detail/js.html, astrobin_apps_images/static/astrobin_apps_images/js/astrobin_apps_images.js
Additionally, fix exiting fullscreen while in Fancybox, and fix Fancybox's expectation that an image is present.
=> (videos) Do not allow videos to be rendered beyond their native size, causing upscaling
