.gitattributes
With `text=auto` in the `.gitattributes` file, cloning the repository on a Linux box ends up doing line ending coversion on every text file.  The result is that the entire repository appears as "modified".
Removing the line lets git do its own automatic line-ending conversion process, which behaves more sanely.
I'd actually recomend removing the other lines as well, but they don't seem to be hurting anything at the moment.
=> Remove text=auto from .gitattributes because it prevents development on linux

astrobin/signals.py
This bug would cause deleted images not to decrease the counter, giving
everyone an extra free image on Free and Lite subscriptions.
=> (subscriptions) Fix leap year bug affecting Free and Lite subscriptions

astrobin/templates/image/detail/image_card.html, astrobin/views/image.py, astrobin_apps_premium/templatetags/astrobin_apps_premium_tags.py
Additionally, move the Resolution entry down to the last secion.
Closes #872
=> (images) Hide empty or zero values from acquisition details card

astrobin/templates/upload.html, astrobin/tests/test_image.py, astrobin/views/__init__.py, astrobin_apps_premium/tests/test_premium.py, astrobin_apps_premium/utils.py
The message should not be shown if the user has another subscription that is valid.
=> (premium) Fix showing "inactive subscription" message on upload page

astrobin/templatetags/tags.py
The default English language uses US date format.
=> (general) Do specify English (US) in language selector

astrobin/admin.py, astrobin/management/commands/merge_makes.py, astrobin/migrations/0001_initial.py, astrobin/models.py, astrobin/tests/test_gear.py
For diversity reasons, it would be nice to try to avoid 'master' and 'slave' terminology in this repository which can be associated to slavery. The master-slave terminology could be problematic for people in several countries which has the history of slavery like Romania, USA and many others. Thank you for considering the proposal. Let me know if any changes in the PR are needed, I would be happy to implement them.
=> Migrate from master-slave language

astrobin/templates/base/user_links_entries.html
The 'Gallery' link in the main user dropdown was renamed to 'Public Gallery', and a link to the user's staging gallery was added.
=> (general) Add staging gallery to dropdown and rename gallery to public gallery

astrobin_apps_images/api/utils.py, docker/docker-compose.yml
This ensures that the chunked upload works well in a multi-server environment.
=> (uploader) Use shared directory for chunks

renovate.json, requirements.txt
They will only be upgraded manually at some point.
=> (infra) Force Django < 2 and elasticsearch < 3

astrobin/views/__init__.py, astrobin/views/registration.py, astrobin_apps_users/services/user_service.py, astrobin_apps_users/tests/test_user_service.py
Additionally, when trying to access a user page with the wrong case,
try to match it in a case insensitive way if non ambiguous.
Closes #1571
=> (users) Forbid new accounts by case-insensitive existing username

astrobin/views/__init__.py
Searching by username is not an exact match, so it would find also users with a username
that is a superstring of this user's username, and then return wrong data.
=> (users) Get user's search query set by id instead of username

astrobin/templates/user/profile/meta.html, astrobin/templatetags/tags.py, astrobin/tests/test_user.py
Don't show anything for accounts with infinite uploads.
=> (users) Show "images used" for Lite 2020 and "uploads used" for free and old Lite

astrobin/management/commands/merge_makes.py, astrobin/management/commands/rename_makes.py, astrobin/stats.py, astrobin/tests/test_utils.py, astrobin/utils.py
I noticed there were a couple of modules defining the same version of this util, this PR unifies them and implement a unique entrypoint for this functionality, additionally, the performance improved by 50%
```Python
>>> s="""
found = []
for i in [1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,1,2,4,4,5,7,2,6,8,91,2,3,1,1,02,3,5,6,4,3,2,4,5,6,8,4,3]:
if i not in found:
found.append(i)
"""
>>> d="""list(set([1,2,3,4,5,1,2,3,4,5,1,2,3,4,5,1,2,4,4,5,7,2,6,8,91,2,3,1,1,02,3,5,6,4,3,2,4,5,6,8,4,3]))"""
>>> timeit.timeit(stmt=s, number=100000)
0.3887138366699219
>>> timeit.timeit(stmt=d, number=100000)
0.17331814765930176
```
=> Unify and improve unique_items

astrobin/tasks.py
This way, if tasks are heavily delayed, they won't have to process too long a queue.
=> (search) Add specific end time to update_index task

astrobin/tests/test_utils.py, astrobin/utils.py
This should fix the issue with unique items when used on nested lists, sorted can't be used anyway on nested lists if those are made by different types
=> Fix unique items on nested lists

astrobin/static/astrobin/scss/astrobin.scss
Hi everyone! I should say that I highly appreciate the effort put into astrobin. I've been loosely using it from time to time.
I've just created an issue (#1861) recently and this PR is my attempt for solving the issue.
First of all, I didn't set up the local development environment, as it seems pretty time-consuming and my fix is quite a small, cosmetic one. But I tried my proposed change in devtools in astrobin.com and it seems to be working without affecting anything else.
I think, in the past `overflow: hidden` might have been added for the purpose of clipping the semi-transparent profile-details layer in the avatar container. But currently that part is not affected by this change.
And here's how it looks after my change:
(hovered on unfollow button)
=> Fix tooltip getting clipped by avatar

astrobin/signals.py, astrobin/views/image.py, astrobin_apps_notifications/tasks.py
If a user has lots of followers, it can be slow.
=> (notifications) Use async task to send notifications about new images

astrobin/signals.py
Saving during is not necessary and only slows down the PATCH requests.
=> (uploader) Perform saving of user/userprofile only after the upload process is finished

astrobin/settings/components/languages.py, astrobin/views/__init__.py
Before this patch, it was set to 0, so not actually preserved, and you'd get the browser's default
language after a browser restart.
=> (general) Fix max age of language cookie

astrobin_apps_images/api/serializers/image_upload_serializer.py
It got broken again when renaming the ImageSerializer.
=> (images) Fix keeping default license after upload from beta uploader (again)

docker/astrobin.env
the BASE_URL of localhost does not correctly reflect the actual BASE_URL of localhost:8083
=> fix BASE_URL to reflect default value

astrobin/models.py, astrobin_apps_platesolving/models/solution.py
Invalidating is quite expensive, so we only invalidate the original uploads and let the thumbnails expires after 30 days.
=> (infra) Don't invalidate cached thumbnails and solution annotations: just let them expire
